#!/usr/bin/env bash

# include repos
source ./repos
echo repos: $repos

# create symlinks
ln -sf ~/.vim/vimrc ~/.vimrc
ln -sf ~/.vim/gvimrc ~/.gvimrc

# install pathogen; see https://github.com/tpope/vim-pathogen#installation
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# install vim plugin repos
cd ~/.vim/bundle
for repo in $repos
do
  git clone https://github.com/$repo
done

# post git clone commands

( cd vimproc.vim && make )

cd -
